import Head from "next/head";
import { useBoundStore } from "@/stores/useBoundStore";

export default function Home() {
  const bears = useBoundStore((state) => state.bears);
  const fishes = useBoundStore((state) => state.fishes);
  const addBear = useBoundStore((state) => state.addBear);
  const addFish = useBoundStore((state) => state.addFish);

  return (
    <>
      <Head>
        <title>Zustand but Redux Style</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="content text-dark">
        <h1>Zustand but Redux Style</h1>
        <section className="content">
          <h3 className="font-normal">Number of bears: {bears}</h3>
          <h3 className="font-normal">Number of fishes: {fishes}</h3>
        </section>
        <section className="content">
          <button className="btn-animated font-bold" onClick={() => addBear()}>
            Add a bear
          </button>
          <button className="btn-animated font-bold" onClick={() => addFish()}>
            Add a fish
          </button>
        </section>
      </section>
    </>
  );
}
